version: "3.4"

services:
  frontend-react:
    build:
      context: "../frontend"
    ports:
      - "3000:3000"
    volumes:
      - "../frontend/public/:/home/node/public:delegated"
      - "../frontend/src/:/home/node/src:delegated"
    container_name: "frontend"

  backend-db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: getitdone
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
      - pgdata:/var/lib/postgresql/data
    container_name: backend-db

  backend:
    depends_on:
      - backend-db
    build:
      context: "../backend"
    ports:
      - "8080:3000"
    environment:
      DATABASE_URL: postgres://user:pass@backend-db:5432/db
    volumes:
      - "../backend/src:/home/node/src:delegated"
    container_name: "backend"

volumes:
  pgdata:
